Added a bunch of files stuff

diff --git a/bashrc/files/brc-files-uploadfile b/bashrc/files/brc-files-uploadfile
--- a/bashrc/files/brc-files-uploadfile
+++ b/bashrc/files/brc-files-uploadfile
@@ -9,7 +9,7 @@ function usage() {
   echo "Usage: brc-files-uploadfile [-h] [-a BRC_AUTHTOKEN] [-r BRC_REGION] \\"
   echo "                            [-t BRC_TENANTID] [-v BRC_VAULTNAME] \\"
   echo "                            -f LOCALFILE -c CONTAINER \\"
-  echo "                            -n NEWFILENAME"
+  echo "                            [-n OBJECTNAME]"
   echo "Example:"
   echo "  # brc-files-uploadfile -a 1a2b3c4d5e6f7g8h9i0j \\"
   echo "                         -t 123456 \\"
@@ -36,10 +36,10 @@ USAGEFLAG=0
 while getopts ":a:c:f:hn:r:v:" arg; do
   case $arg in
     a) BRC_AUTHTOKEN=$OPTARG;;
-    c) CONTAINER=$OPTARG;;
+    c) CONTAINER="$OPTARG";;
     f) LOCALFILE="$OPTARG";;
     h) usage && exit 0;;
-    n) NEWFILENAME="$OPTARG";;
+    n) OBJECTNAME="$OPTARG";;
     r) BRC_REGION=$OPTARG;;
     v) BRC_VAULTNAME=$OPTARG;;
     :) echo "ERROR: Option -$OPTARG requires an argument."
@@ -50,39 +50,31 @@ while getopts ":a:c:f:hn:r:v:" arg; do
 done #End arguments
 shift $(($OPTIND - 1))
 
-if [ -z "$BRC_AUTHTOKEN" ]; then
-  echo "ERROR: Must define BRC_AUTHTOKEN in environment or argument"
-  USAGEFLAG=1
-fi
-if [ -z "$BRC_REGION" ]; then
-  echo "ERROR: Must define BRC_REGION in environment or argument"
-  USAGEFLAG=1
-fi
-if [ -z "$LOCALFILE" ]; then
-  echo "ERROR: Must define LOCALFILE as argument"
-  USAGEFLAG=1
-elif [ ! -f "$LOCALFILE" ]; then
-  echo "ERROR: Can not access $LOCALFILE - does it exist?"
-  USAGEFLAG=1
-fi
-if [ -z "$CONTAINER" ]; then
-  echo "ERROR: Must define CONTAINER as argument"
-  USAGEFLAG=1
-fi
-if [ -z "$BRC_VAULTNAME" ]; then
-  echo "ERROR: Must define BRC_VAULTNAME in environment or argument"
-  USAGEFLAG=1
-fi
-
+for ARG in BRC_AUTHTOKEN BRC_REGION BRC_VAULTNAME; do
+  if [ -z "${!ARG}" ]; then
+    echo "ERROR: Must define ${!ARG} in environment or argument"
+    USAGEFLAG=1
+  fi
+done
+for ARG in CONTAINER LOCALFILE; do
+  if [ -z "${!ARG}" ]; then
+    echo "ERROR: Must define ${!ARG} as argument"
+    USAGEFLAG=1
+  fi
+done
 if [ $USAGEFLAG -ne 0 ]; then
   usage && exit 1
+fi
+if [ ! -f "$LOCALFILE" ]; then
+  echo "ERROR: Can not access $LOCALFILE - does it exist?"
+  exit 1
 fi
 
 FILES_ENDPOINT=$( $BRCUTIL/brc-util-filesendpoint -r $BRC_REGION )
 #CDN_ENDPOINT=$( $BRCUTIL/brc-util-cdnendpoint -r $BRC_REGION )
 
-if [ -z "$NEWFILENAME" ]; then
-  NEWFILENAME=$( basename "$LOCALFILE" )
+if [ -z "$OBJECTNAME" ]; then
+  OBJECTNAME=$( basename "$LOCALFILE" )
 fi
 
 
@@ -90,21 +82,31 @@ function uploadSmallFile() {
   local FILE="$1"
   local CFNAME="$2"
   local MD5="$3"
-  DATA=$( curl --write-out \\n%{http_code} --silent --output - \
-               $FILES_ENDPOINT/$BRC_VAULTNAME/$CONTAINER/$CFNAME \
-               -T <( cat "$FILE" ) \
-               -X PUT \
-               -H "X-Auth-Token: $BRC_AUTHTOKEN" \
-               -H "ETag: $MD5" \
-            2>/dev/null )
-  RETVAL=$?
-  CODE=$( echo "$DATA" | tail -n 1 )
-  # Check for failed API call
-  if [ $RETVAL -ne 0 ]; then
-    errorcurlfail
-  elif [[ $(echo "$CODE" | grep -cE '^2..$') -eq 0 ]]; then
-    errornot200 $CODE $( echo "$DATA" | head -n -1 )
-  fi
+  echo "Creating object $CFNAME"
+  # Retry loop - try 10 times
+  for x in `seq 1 10`; do
+    DATA=$( curl --write-out \\n%{http_code} --silent --output - \
+                 $FILES_ENDPOINT/$BRC_VAULTNAME/"$CONTAINER"/"$CFNAME" \
+                 -X PUT \
+                 -T "$FILE" \
+                 -H "X-Auth-Token: $BRC_AUTHTOKEN" \
+                 -H "ETag: $MD5" \
+              2>/dev/null )
+    RETVAL=$?
+    CODE=$( echo "$DATA" | tail -n 1 )
+    # Check for failed API call
+    if [ $RETVAL -ne 0 ]; then
+      errorcurlfail
+    elif [[ $(echo "$CODE" | grep -cE '^2..$') -gt 0 ]]; then
+      return 0
+    elif [ $CODE -eq 422 ]; then
+      # md5sum error - retry
+      continue
+    else #Not 200, not 422
+      errornot200 $CODE $( echo "$DATA" | head -n -1 )
+    fi
+  done
+  return 1
 }
 
 
@@ -112,20 +114,34 @@ function uploadLargeFile() {
   local FILE="$1"
   local CFNAME="$2"
   local SIZE=$( du -B 1G "$FILE" | awk '{print $1}' )
+  local TMPFILE="/tmp/bashrc.$(( $RANDOM * $RANDOM ))"
+  echo "Object '$CFNAME' >4G.  Splitting into 1G segments."
+  #mkfifo $TMPFILE
+  # Upload all the file segments, 1G at a time
   for COUNT in $( seq -w 0 $(( $SIZE - 1 )) ); do
-    # bs=4096 -- Attempt to optimize read speeds by matching block size on drive architecture
-    # count=262144 == 1G/4096 -- Read 1G
-    # skip=262144 * $COUNT -- Skip previously-read 1G chunks
-    local MD5=$( dd if="$FILE" bs=4k count=262144 seek=$(( 262144 * $COUNT )) \
-                   | md5sum | awk '{print $1}' )
-    uploadSmallFile <( dd if="$FILE" bs=4k count=262144 seek=$(( 262144 * $COUNT )) ) \
-                    ${CFNAME}-$COUNT \
-                    $MD5
-  done
+    # Retry loop - try 10 times
+    for x in `seq 1 10`; do
+      # bs=4096 -- Attempt to optimize read speeds by matching block size on drive architecture
+      # count=262144 == 1G/4096 -- Read 1G
+      # skip=262144 * $COUNT -- Skip previously-read 1G chunks
+      local MD5=$( dd if="$FILE" bs=4k count=262144 seek=$(( 262144 * $COUNT )) 2>/dev/null \
+                     | md5sum | awk '{print $1}' )
+      #uploadSmallFile $TMPFILE \
+      uploadSmallFile <( dd if="$FILE" bs=4k count=262144 seek=$(( 262144 * $COUNT )) 2>/dev/null ) \
+                      "${CFNAME}"-$COUNT \
+                      $MD5
+      # If segment uploaded successfully, break the x(1-10) retry loop
+      # Stay in the COUNT loop.  ie: Do the next segment.
+      if [ $? -eq 0 ]; then
+        break
+      fi
+    done #End for x(1-10)
+  done #End for COUNT
+  #rm -f $TMPFILE
 
   # Create/Upload an empty dynamic manifest file
   DATA=$( curl --write-out \\n%{http_code} --silent --output - \
-               $FILES_ENDPOINT/$BRC_VAULTNAME/$CONTAINER/$CFNAME \
+               $FILES_ENDPOINT/$BRC_VAULTNAME/"$CONTAINER"/"$CFNAME" \
                -T /dev/null \
                -X PUT \
                -H "X-Auth-Token: $BRC_AUTHTOKEN" \
@@ -139,7 +155,6 @@ function uploadLargeFile() {
   elif [[ $(echo "$CODE" | grep -cE '^2..$') -eq 0 ]]; then
     errornot200 $CODE $( echo "$DATA" | head -n -1 )
   fi
-  DATA=$( echo "$DATA" | head -n -1 | $BRCUTIL/brc-util-json.tool )
 }
 
 
@@ -147,17 +162,14 @@ function uploadLargeFile() {
 # Test the source file.
 # If > 4G then split & upload each piece individually, then create a dynamic manifest
 # http://docs.rackspace.com/files/api/v1/cf-devguide/content/Large_Object_Creation-d1e2019.html
-#
-MAXSIZE=$(( 4 * 1024 * 1024 * 1024 ))
-MAXSIZE=$(( 1 * 1024 * 1024 * 1024 ))
-if [ $( stat -c%s "$LOCALFILE" ) -lt $MAXSIZE ]; then
-  # Just upload it.  Function this.
+MAXSIZE=$(( 5 * 1024 * 1024 * 1024 ))
+if [ $( du -B 1G "$LOCALFILE" | awk '{print $1}' ) -lt $MAXSIZE ]; then
   MD5=$( md5sum "$LOCALFILE" | awk '{print $1}' )
-  uploadSmallFile "$LOCALFILE" "$NEWFILENAME" "$MD5"
+  uploadSmallFile "$LOCALFILE" "$OBJECTNAME" "$MD5"
 else
-  uploadLargeFile "$LOCALFILE" "$NEWFILENAME"
+  uploadLargeFile "$LOCALFILE" "$OBJECTNAME"
 fi
 
-echo "Data:"
-echo "$DATA"
+echo "Response code: $CODE"
 exit 0
+
