Fixing command-line args and adding curl error handling

diff --git a/bashrc/identity/brc-identity-listroles b/bashrc/identity/brc-identity-listroles
--- a/bashrc/identity/brc-identity-listroles
+++ b/bashrc/identity/brc-identity-listroles
@@ -2,40 +2,55 @@
 
 #
 # List available roles on the given cloud account
-
 function usage() {
-  echo "Usage: brc-identity-listroles [-t BRC_TENANTID] [-a BRC_AUTHTOKEN]"
+  echo "Usage: brc-identity-listroles [-a BRC_AUTHTOKEN] [-h]"
   echo "Example:"
-  echo "  # brc-identity-listroles -t 123456 -a 1a2b3c4d5e6f7g8h9i0j"
+  echo "  # brc-identity-listroles -a 1a2b3c4d5e6f7g8h9i0j"
   echo "Example:"
-  echo "  # export BRC_TENANTID=123456"
   echo "  # export BRC_AUTHTOKEN=1a2b3c4d5e6f7g8h9i0j"
   echo "  # brc-identity-listroles"
 }
 
-while getopts ":ht:a:" arg; do
+USAGEFLAG=0
+while getopts ":ha:" arg; do
   case $arg in
-    t) BRC_TENANTID=$OPTARG;;
     a) BRC_AUTHTOKEN=$OPTARG;;
-    *) usage && exit 1;;
+    h) usage && exit 0;;
+    :) echo "ERROR: Option -$OPTARG requires an argument."
+       USAGEFLAG=1;;
+    *) echo "ERROR: Invalid option: -$OPTARG"
+       USAGEFLAG=1;;
   esac
 done #End arguments
 shift $(($OPTIND - 1))
 
-if [ -z $BRC_TENANTID ]; then
-  echo "ERROR: Must define BRC_TENANTID in environment or argument"
-  usage && exit 1
-elif [ -z $BRC_AUTHTOKEN ]; then
+if [ -z $BRC_AUTHTOKEN ]; then
   echo "ERROR: Must define BRC_AUTHTOKEN in environment or argument"
+  USAGEFLAG=1
+fi
+
+if [ $USAGEFLAG -ne 0 ]; then
   usage && exit 1
 fi
 
-ENDPOINT=$IDENTITY_ENDPOINT
-DATA=$( curl $ENDPOINT/OS-KSADM/roles \
+DATA=$(curl --write-out \\n%{http_code} --silent --output - \
+            $IDENTITY_ENDPOINT/OS-KSADM/roles \
              -H "Content-Type: application/json" \
              -H "X-Auth-Token: $BRC_AUTHTOKEN" \
-          2>/dev/null | brc-json.tool )
+          2>/dev/null )
+CODE=$( echo "$DATA" | tail -n 1 )
 
+# Check for failed API call
+if [[ $(echo "$CODE" | grep -cE '^2..$') -eq 0 ]]; then
+  echo "$DATA" | head -n -1
+  echo
+  echo "ERROR: API call unsuccessful"
+  echo "Response code: $CODE"
+  echo "Raw response data above."
+  exit 1
+fi
+
+DATA=$( echo "$DATA" | head -n -1 | brc-json.tool )
 IDS=$( echo "$DATA" \
         | sed -n 's/bashrc~roles~id.\([0-9]*\)~.*$/\1/p' )
 
diff --git a/bashrc/identity/brc-identity-listusers b/bashrc/identity/brc-identity-listusers
--- a/bashrc/identity/brc-identity-listusers
+++ b/bashrc/identity/brc-identity-listusers
@@ -2,9 +2,8 @@
 
 #
 # List all users on the given cloud account
-
 function usage() {
-  echo "Usage: brc-identity-listusers [-t BRC_TENANTID] [-a BRC_AUTHTOKEN]"
+  echo "Usage: brc-identity-listusers [-h] [-t BRC_TENANTID] [-a BRC_AUTHTOKEN]"
   echo "Example:"
   echo "  # brc-identity-listusers -t 123456 -a 1a2b3c4d5e6f7g8h9i0j"
   echo "Example:"
@@ -13,35 +12,57 @@ function usage() {
   echo "  # brc-identity-listusers"
 }
 
+USAGEFLAG=0
 while getopts ":ht:a:" arg; do
   case $arg in
     t) BRC_TENANTID=$OPTARG;;
     a) BRC_AUTHTOKEN=$OPTARG;;
-    *) usage && exit 1;;
+    h) usage && exit 0;;
+    :) echo "ERROR: Option -$OPTARG requires an argument."
+       USAGEFLAG=1;;
+    *) echo "ERROR: Invalid option: -$OPTARG"
+       USAGEFLAG=1;;
   esac
 done #End arguments
 shift $(($OPTIND - 1))
 
 if [ -z $BRC_TENANTID ]; then
   echo "ERROR: Must define BRC_TENANTID in environment or argument"
-  usage && exit 1
+  USAGEFLAG=1
 elif [ -z $BRC_AUTHTOKEN ]; then
   echo "ERROR: Must define BRC_AUTHTOKEN in environment or argument"
+  USAGEFLAG=1
+fi
+
+if [ $USAGEFLAG -ne 0 ]; then
   usage && exit 1
 fi
 
-ENDPOINT=$IDENTITY_ENDPOINT
-USERDATA=$( curl $ENDPOINT/users \
-                 -H "Content-Type: application/json" \
-                 -H "X-Auth-Token: $BRC_AUTHTOKEN" \
-              2>/dev/null | brc-json.tool )
+DATA=$( curl --write-out \\n%{http_code} --silent --output - \
+             $IDENTITY_ENDPOINT/users \
+             -H "Content-Type: application/json" \
+             -H "X-Auth-Token: $BRC_AUTHTOKEN" \
+          2>/dev/null )
+CODE=$( echo "$DATA" | tail -n 1 )
 
-USERIDS=$( echo "$USERDATA" \
+# Check for failed API call
+if [[ $(echo "$CODE" | grep -cE '^2..$') -eq 0 ]]; then
+  echo "$DATA" | head -n -1
+  echo
+  echo "ERROR: API call unsuccessful"
+  echo "Response code: $CODE"
+  echo "Raw response data above."
+  exit 1
+fi
+
+DATA=$( echo "$DATA" | head -n -1 | brc-json.tool )
+
+USERIDS=$( echo "$DATA" \
              | sed -n 's/bashrc~users~username.\([0-9]*\)~.*$/\1/p' )
 
 # Just clean up the output a bit
 echo ---
 for x in $USERIDS; do
-  echo "$USERDATA" | grep "\.$x~"
+  echo "$DATA" | grep "\.$x~"
   echo ---
 done
